/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => TextBundleExportPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");

// zip.ts
var CRC_TABLE = (() => {
  const table = new Uint32Array(256);
  for (let n = 0; n < 256; n++) {
    let c = n;
    for (let k = 0; k < 8; k++) {
      c = c & 1 ? 3988292384 ^ c >>> 1 : c >>> 1;
    }
    table[n] = c >>> 0;
  }
  return table;
})();
function crc32(data) {
  let crc = 4294967295;
  for (let i = 0; i < data.length; i++) {
    crc = CRC_TABLE[(crc ^ data[i]) & 255] ^ crc >>> 8;
  }
  return (crc ^ 4294967295) >>> 0;
}
function createZip(entries, date = new Date()) {
  const encoder = new TextEncoder();
  const dosTime = date.getHours() << 11 | date.getMinutes() << 5 | date.getSeconds() >> 1;
  const dosDate = (date.getFullYear() - 1980 & 127) << 9 | date.getMonth() + 1 << 5 | date.getDate();
  const prepared = entries.map((e) => {
    const nameBytes = encoder.encode(e.name);
    return {
      nameBytes,
      data: e.data,
      crc: crc32(e.data),
      isDir: e.name.endsWith("/"),
      offset: 0
    };
  });
  let localSize = 0;
  for (const p of prepared)
    localSize += 30 + p.nameBytes.length + p.data.length;
  let centralSize = 0;
  for (const p of prepared)
    centralSize += 46 + p.nameBytes.length;
  const total = localSize + centralSize + 22;
  const out = new Uint8Array(total);
  const view = new DataView(out.buffer);
  let pos = 0;
  for (const p of prepared) {
    p.offset = pos;
    view.setUint32(pos, 67324752, true);
    view.setUint16(pos + 4, 20, true);
    view.setUint16(pos + 6, 2048, true);
    view.setUint16(pos + 8, 0, true);
    view.setUint16(pos + 10, dosTime, true);
    view.setUint16(pos + 12, dosDate, true);
    view.setUint32(pos + 14, p.crc, true);
    view.setUint32(pos + 18, p.data.length, true);
    view.setUint32(pos + 22, p.data.length, true);
    view.setUint16(pos + 26, p.nameBytes.length, true);
    view.setUint16(pos + 28, 0, true);
    out.set(p.nameBytes, pos + 30);
    out.set(p.data, pos + 30 + p.nameBytes.length);
    pos += 30 + p.nameBytes.length + p.data.length;
  }
  const centralStart = pos;
  for (const p of prepared) {
    view.setUint32(pos, 33639248, true);
    view.setUint16(pos + 4, 20, true);
    view.setUint16(pos + 6, 20, true);
    view.setUint16(pos + 8, 2048, true);
    view.setUint16(pos + 10, 0, true);
    view.setUint16(pos + 12, dosTime, true);
    view.setUint16(pos + 14, dosDate, true);
    view.setUint32(pos + 16, p.crc, true);
    view.setUint32(pos + 20, p.data.length, true);
    view.setUint32(pos + 24, p.data.length, true);
    view.setUint16(pos + 28, p.nameBytes.length, true);
    view.setUint16(pos + 30, 0, true);
    view.setUint16(pos + 32, 0, true);
    view.setUint16(pos + 34, 0, true);
    view.setUint16(pos + 36, 0, true);
    view.setUint32(pos + 38, p.isDir ? 16 : 0, true);
    view.setUint32(pos + 42, p.offset, true);
    out.set(p.nameBytes, pos + 46);
    pos += 46 + p.nameBytes.length;
  }
  view.setUint32(pos, 101010256, true);
  view.setUint16(pos + 4, 0, true);
  view.setUint16(pos + 6, 0, true);
  view.setUint16(pos + 8, prepared.length, true);
  view.setUint16(pos + 10, prepared.length, true);
  view.setUint32(pos + 12, pos - centralStart, true);
  view.setUint32(pos + 16, centralStart, true);
  view.setUint16(pos + 20, 0, true);
  return out.buffer;
}

// main.ts
var DEFAULT_SETTINGS = {
  outputFormat: "textpack",
  exportLocation: "same",
  customFolder: ""
};
var IMAGE_EXTENSIONS = /* @__PURE__ */ new Set([
  "png",
  "jpg",
  "jpeg",
  "gif",
  "bmp",
  "svg",
  "webp",
  "avif",
  "tif",
  "tiff",
  "heic",
  "heif",
  "ico"
]);
var INFO_JSON = {
  transient: false,
  type: "net.daringfireball.markdown",
  version: 2,
  creatorIdentifier: "md.obsidian.plugin.textbundle-export"
};
var TextBundleExportPlugin = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    this.addRibbonIcon("package", "Export to TextBundle", () => {
      const file = this.app.workspace.getActiveFile();
      if (file && file.extension === "md") {
        void this.exportNote(file);
      } else {
        new import_obsidian.Notice("No active Markdown note.");
      }
    });
    this.addCommand({
      id: "export-current-note-to-textbundle",
      name: "Export current note to TextBundle",
      checkCallback: (checking) => {
        const file = this.app.workspace.getActiveFile();
        if (file && file.extension === "md") {
          if (!checking)
            void this.exportNote(file);
          return true;
        }
        return false;
      }
    });
    this.registerEvent(
      this.app.workspace.on("file-menu", (menu, file) => {
        if (file instanceof import_obsidian.TFile && file.extension === "md") {
          menu.addItem(
            (item) => item.setTitle("Export to TextBundle").setIcon("package").onClick(() => void this.exportNote(file))
          );
        }
      })
    );
    this.addSettingTab(new TextBundleSettingTab(this.app, this));
  }
  async loadSettings() {
    this.settings = Object.assign(
      {},
      DEFAULT_SETTINGS,
      await this.loadData()
    );
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  /**
   * Collect the image files referenced by the note.
   * Handles wiki embeds `![[img.png]]` and Markdown images `![](img.png)`.
   * The note's text is never modified — images are only copied as-is.
   */
  collectImages(file, content) {
    var _a;
    const images = [];
    const seen = /* @__PURE__ */ new Set();
    const resolve = (rawLink) => {
      let linkpath = rawLink.split("|")[0].split("#")[0].split("^")[0].trim();
      if (!linkpath)
        return;
      if (/^(https?|data|obsidian):/i.test(linkpath))
        return;
      try {
        linkpath = decodeURIComponent(linkpath);
      } catch (e) {
      }
      const dest = this.app.metadataCache.getFirstLinkpathDest(
        linkpath,
        file.path
      );
      if (dest && IMAGE_EXTENSIONS.has(dest.extension.toLowerCase()) && !seen.has(dest.path)) {
        seen.add(dest.path);
        images.push(dest);
      }
    };
    const wikiRe = /!\[\[([^\]]+)\]\]/g;
    let m;
    while ((m = wikiRe.exec(content)) !== null)
      resolve(m[1]);
    const mdRe = /!\[[^\]]*\]\(\s*(?:<([^>]+)>|([^)\s]+))/g;
    while ((m = mdRe.exec(content)) !== null)
      resolve((_a = m[1]) != null ? _a : m[2]);
    return images;
  }
  async exportNote(file) {
    try {
      const content = await this.app.vault.read(file);
      const images = this.collectImages(file, content);
      const infoJson = JSON.stringify(
        { ...INFO_JSON, createdAt: new Date().toISOString() },
        null,
        2
      );
      const destFolder = await this.resolveDestFolder(file);
      const usedNames = /* @__PURE__ */ new Set();
      const assetName = (f) => {
        let name = f.name;
        if (!usedNames.has(name.toLowerCase())) {
          usedNames.add(name.toLowerCase());
          return name;
        }
        const base = f.basename;
        let i = 2;
        while (usedNames.has(`${base}-${i}.${f.extension}`.toLowerCase())) {
          i++;
        }
        name = `${base}-${i}.${f.extension}`;
        usedNames.add(name.toLowerCase());
        return name;
      };
      const bundleBase = sanitizeName(file.basename);
      if (this.settings.outputFormat === "textpack") {
        const encoder = new TextEncoder();
        const entries = [
          // the note text is written out byte-for-byte unchanged
          { name: "text.md", data: encoder.encode(content) },
          { name: "info.json", data: encoder.encode(infoJson) },
          { name: "assets/", data: new Uint8Array(0) }
        ];
        for (const img of images) {
          const data = await this.app.vault.readBinary(img);
          entries.push({
            name: `assets/${assetName(img)}`,
            data: new Uint8Array(data)
          });
        }
        const bundle = createZip(entries);
        const outPath = this.availablePath(
          destFolder,
          `${bundleBase}.textpack`
        );
        await this.app.vault.createBinary(outPath, bundle);
        new import_obsidian.Notice(
          `Exported ${images.length} image(s) → ${outPath}`
        );
      } else {
        const folderPath = this.availablePath(
          destFolder,
          `${bundleBase}.textbundle`
        );
        await this.ensureFolder(folderPath);
        await this.app.vault.create(`${folderPath}/text.md`, content);
        await this.app.vault.create(
          `${folderPath}/info.json`,
          infoJson
        );
        await this.app.vault.createFolder(`${folderPath}/assets`);
        for (const img of images) {
          const data = await this.app.vault.readBinary(img);
          await this.app.vault.createBinary(
            `${folderPath}/assets/${assetName(img)}`,
            data
          );
        }
        new import_obsidian.Notice(
          `Exported ${images.length} image(s) → ${folderPath}`
        );
      }
    } catch (e) {
      console.error("TextBundle export failed", e);
      new import_obsidian.Notice(
        `TextBundle export failed: ${e instanceof Error ? e.message : String(e)}`
      );
    }
  }
  async resolveDestFolder(file) {
    var _a, _b, _c;
    const loc = this.settings.exportLocation;
    if (loc === "root")
      return "";
    if (loc === "custom") {
      const folder = (0, import_obsidian.normalizePath)(this.settings.customFolder.trim());
      await this.ensureFolder(folder);
      return folder;
    }
    return ((_a = file.parent) == null ? void 0 : _a.path) === "/" ? "" : (_c = (_b = file.parent) == null ? void 0 : _b.path) != null ? _c : "";
  }
  async ensureFolder(path) {
    const parts = (0, import_obsidian.normalizePath)(path).split("/").filter(Boolean);
    let current = "";
    for (const part of parts) {
      current = current ? `${current}/${part}` : part;
      if (!this.app.vault.getAbstractFileByPath(current)) {
        await this.app.vault.createFolder(current);
      }
    }
  }
  /** Return a collision-free path inside `folder` for a file/folder name. */
  availablePath(folder, name) {
    const dot = name.lastIndexOf(".");
    const base = dot > 0 ? name.slice(0, dot) : name;
    const ext = dot > 0 ? name.slice(dot) : "";
    const join = (n) => (0, import_obsidian.normalizePath)(folder ? `${folder}/${n}` : n);
    let candidate = join(name);
    let i = 1;
    while (this.app.vault.getAbstractFileByPath(candidate)) {
      candidate = join(`${base} ${i}${ext}`);
      i++;
    }
    return candidate;
  }
};
function sanitizeName(name) {
  const cleaned = name.replace(/[\\/:*?"<>|]/g, "-").trim();
  return cleaned.length > 0 ? cleaned : "note";
}
var TextBundleSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Output format").setDesc(
      "TextPack (.textpack) is a single zipped file; TextBundle (.textbundle) is a plain folder. The Markdown text itself is never modified in either case."
    ).addDropdown(
      (drop) => drop.addOption("textpack", "TextPack (.textpack, zipped)").addOption("textbundle", "TextBundle (.textbundle, folder)").setValue(this.plugin.settings.outputFormat).onChange(async (value) => {
        this.plugin.settings.outputFormat = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Export location").setDesc("Where the exported bundle is saved in your vault.").addDropdown(
      (drop) => drop.addOption("same", "Same folder as the note").addOption("root", "Vault root").addOption("custom", "Custom folder").setValue(this.plugin.settings.exportLocation).onChange(async (value) => {
        this.plugin.settings.exportLocation = value;
        await this.plugin.saveSettings();
        this.display();
      })
    );
    if (this.plugin.settings.exportLocation === "custom") {
      new import_obsidian.Setting(containerEl).setName("Custom export folder").setDesc("Folder inside the vault, created if missing.").addText(
        (text) => text.setPlaceholder("e.g. exports").setValue(this.plugin.settings.customFolder).onChange(async (value) => {
          this.plugin.settings.customFolder = value;
          await this.plugin.saveSettings();
        })
      );
    }
  }
};
